version: '3.9'

services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      mynetwork:
    container_name: postgres

  app:
    build:
      context: ./
      dockerfile: cmd/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      mynetwork:
    command: sh -c "sleep 10 && ./app"


volumes:
  db:
    driver: local

networks:
  mynetwork:
